name: awesomemusic
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  audio_service: ^0.17.0
  audio_session: ^0.1.0
  audiotagger: ^2.2.0
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  des_plugin: ^0.0.3
  dio: ^4.0.0
  flutter_cache: ^0.1.0
  get: ^4.1.4
  get_storage: ^2.0.2
  google_fonts: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  http: ^0.13.1
  just_audio: ^0.7.4+1
  path: ^1.7.0
  permission_handler: ^7.0.0
  sn_progress_dialog: ^1.0.1
  palette_generator: ^0.3.0
  flutter_neumorphic_null_safety: ^3.2.0
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
